---
kind: theorem
status: active
input_types: []
depends_on: [integers, mediant, fixed_point]
consequences: [klein_bottle, duty_function, proof_A_gravity, proof_B_quantum, spatial_dimension]
---

# Three dimensions

## Statement

Given the [mediant](mediant.md) axiom and a continuum completion of
its action on rationals, the associated Lie group is
$\mathrm{SL}(2, \mathbb{R})$ and

$$\dim \mathrm{SL}(2, \mathbb{R}) \;=\; 3.$$

If the spatial manifold of the framework is taken to be this group
(step 3 below), then $d = 3$.

## Proof

Steps 1, 2, and 4 are standard; step 3 invokes an external
uniqueness result.

### 1. The mediant is the column-sum action of $\mathrm{SL}(2, \mathbb{Z})$

Write the pair $(a/b,\, c/d)$ as the matrix

$$M \;=\; \begin{pmatrix} a & c \\ b & d \end{pmatrix}.$$

The mediant $a/b \oplus c/d = (a+c)/(b+d)$ is the column-sum of $M$.
Two fractions are Farey neighbors iff $|ad - bc| = 1$, i.e. iff
$\det M = \pm 1$.  Restricting to $\det M = +1$, consistent with
the orientation of the Farey ordering, gives $\mathrm{SL}(2, \mathbb{Z})$.

### 2. The continuum completion is $\mathrm{SL}(2, \mathbb{R})$

The action extends continuously from rational denominators to real
denominators as the standard Möbius action on the upper half plane
$\mathbb{H}^2$:

$$\begin{pmatrix} a & c \\ b & d \end{pmatrix} \cdot z
  \;=\; \frac{az + c}{bz + d}, \qquad z \in \mathbb{H}^2.$$

Continuity is the minimal extension preserving the Farey ordering.

### 3. Identification of the spatial manifold with the group

If the spatial manifold $M$ is taken to carry a transitive action of
$\mathrm{SL}(2, \mathbb{R})$ with the mediant-induced adjacency, then
$M \cong \mathrm{SL}(2, \mathbb{R}) / H$ for some closed subgroup $H$.
Requiring the adjacency to be generated by a *unique* group element
(the mediant operation is deterministic on Farey-neighbor pairs) is
consistent with $H$ trivial, so $M \cong \mathrm{SL}(2, \mathbb{R})$.

The force of this step is an identification, not a derivation from the
other axioms in this repository.  The Bianchi classification of
three-dimensional Lie groups is what picks out
$\mathrm{SL}(2, \mathbb{R})$ as the relevant simple non-compact case;
see [`lie_group_characterization`](lie_group_characterization.md).

### 4. Dimension count

$\mathrm{SL}(2, \mathbb{R})$ is the codimension-one submanifold
$\{M \in \mathbb{R}^{2 \times 2} : \det M = 1\}$, so

$$\dim \mathrm{SL}(2, \mathbb{R}) \;=\; 2^2 - 1 \;=\; 3.$$

The Iwasawa decomposition $KAN$ gives a compact rotation
$K = \mathrm{SO}(2)$, a one-parameter hyperbolic subgroup $A$, and a
parabolic subgroup $N$.  The three factors account for the three
dimensions.

## Remarks

- **Spatial dimension only.**  This theorem fixes $d = 3$.  The time
  direction is a separate argument via complexification
  $\mathrm{SL}(2, \mathbb{R}) \to \mathrm{SL}(2, \mathbb{C})$, yielding
  the signature $(3, 1)$; see
  [`minkowski_signature`](minkowski_signature.md).
- **Where the load is carried.**  Steps 1, 2, and 4 are
  direct computations.  Step 3 is the substantive claim: it asserts
  that the framework's spatial manifold is $\mathrm{SL}(2, \mathbb{R})$
  itself rather than a quotient or another group of the same dimension.
  That assertion is the content of the theorem.

## Corollaries

- The [duty-function](duty_function.md) exponent equals
  $\dim \mathrm{SL}(2, \mathbb{R})$; the two 3's are the same 3.
- The [Klein-bottle](klein_bottle.md) quotient in which the gauge
  structure lives is defined on a product of two copies of
  $\mathrm{SL}(2, \mathbb{R})$ under an antiperiodic identification.
